src/stories/Button.stories.ts
src/stories/Header.stories.ts
tsconfig.json

1. TS4023 오류 해결
2. TS5096 오류 해결

TypeScript build 오류 임시 해결

---

api/proxy.js

################
Chore : Vercel Functions 추가
################
프론트의 https 사용을 위해서 Vercel Functions를 추가

[Chore 🚀] Vercel Functions 추가

---

src/components/Navbar/NavDropDown.tsx

로그아웃 api 확인 없이 우선적으로 로그아웃이 작동될 수 있도록 
```
localStorage.clear()
navigate("/")
window.location.reload()
```
부분을 로그아웃을 시도했을 때와 시도하고 오류가 발생했을 경우 모두에 추가하여 임시적으로 로그아웃이 되도록하였다.

[Fix 🔨]  로그아웃 임시 가동

---

package-lock.json
package.json
src/components/Accordion/Accordion.stories.tsx
src/components/Accordion/Content.tsx

[Fix 🪛] 빌드 오류 수정

---

src/components/Accordion/Content.tsx

[Chore 🚀] 빌드오류 수정

---

src/apis/domain/bodypart.ts
src/components/SearchField/SearchField.tsx
src/components/SearchField/StyledSearchField.ts
src/hooks/query/useGetBodyPart.ts
src/pages/Home/StyledHome.ts
src/pages/Recommend/BodyPart/BodyPart.tsx
src/pages/Search/Search.tsx
src/pages/Search/StyledSearch.ts
src/types/type.ts

- 데이터 오류에 따른 추천 페이지 bodypart 기본 이미지 추가
- 상대경로 오류로 인한 Home 페이지 로고 오류 수정

[Fix 🪛] Bodypart 기본 이미지 추가

---

src/components/SearchField/SearchField.stories.tsx

[Fix 🪛] SearchField control 스토리북 오류 수정

---

.github/workflows/main.yml

[Chore 🚀] 배포 테스트

---

src/components/Accordion/Accordion.stories.tsx

#209 
Accordion의 Header에 onOpen 함수를 넘기지 않아서 발생한 오류로 void 함수를 넘겨서 오류 수정

[Fix 🪛] Header에 onOpen함수는 void로 넘겨서 수정

---

src/components/CheckBox/CheckBox.stories.tsx
src/components/Input/Input.stories.tsx

[Feat ✏️] Input 컴포넌트 스토리북 구현

---

src/apis/instance.ts
src/pages/Login/Login.tsx
src/pages/Login/StyledLogin.ts

[Fix 🪛] 로그인시 rememberMe를 항상 true로 유지

---

src/pages/Login/Login.tsx

[Refactoring ⚙️] rememberMe true로 유지

---

src/components/Button/RoundButton.tsx
src/store/useModalStore.ts

[Fix 🪛] 타입관련 빌드오류 수정

---

package-lock.json
package.json
src/apis/domain/myfit.ts
src/components/Icon/Icon.tsx
src/components/MyWorkout/MyWorkout.tsx
src/components/Navbar/Navbar.tsx
src/hooks/query/useGetMyRoutines.ts
src/pages/MyPage/My/DragAndDrop.tsx
src/pages/MyPage/My/StyledMyPage.ts
src/types/type.ts

[Refactor ⚙️] Mypage 개선작업

---

src/pages/MyPage/My/MyPage.tsx

[Refactor ⚙️] 루틴 목록 기능 개선

---

.github/workflows/main.yml

#288 
개발 레포 상태를 배포 레포에 완전히 덮어씌우게 githubAction 임시 변경

[Chore 🚀]  개발 레포와 배포 레포 상태 일치 작업

---

.github/workflows/main.yml

#288 
githubAction clone 디렉토리 여부 확인하도록 수정

[Chore 🚀] 개발 레포와 배포레포 상태 동기화

---

src/components/Button/RoundButton.tsx
src/pages/Signup/BodyFigure/components/Figure/StyledFigure.ts

#288 
병합 과정에서 imcomming 코드를 current 코드와 함께 남긴 실수를 발견하여 수정

개발 레포와 배포 레포 병합 오류 수정

---

.github/workflows/main.yml

#288 
클론 디렉토리 재사용 가능하도록 수정하여 효율적으로 병합되도록

클론 디렉토리 재사용 가능하도록 수정

---

.github/workflows/main.yml

#288 
기존에 병합 성공했던 workflow로 임시 되돌려둠

기존에 병합 성공했던 workflow로 임시 변경

---

.github/workflows/main.yml

#288 
배포 레포지토리 default 브랜치명을 deploy로 변경

배포 레포 브랜치명 변경

---

.github/workflows/main.yml

[Chore 🚀] 배포 레포지토리 데이터 삭제로직 제거

---

.github/workflows/main.yml

[Chore 🚀] 강제푸시적용

---

.github/workflows/chromatic.yml
.github/workflows/main.yml

#314 
- 로컬 레포지토리와 원격 레포지토리를 -u 명령어로 연결

[Chore 🚀] remote 테스트
